reviews:
  auto_review: true         # enable automatic reviews
  review_status: true       # show review status (set to false to hide the message)
  branches:
    include:
      - "*"                # run on all branches
